### ISSUE TITLE
data mismatch between http-client and server data

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/tbdex-js#236]
when upgrading examplars, I hit this issue many times: 

```
file:///Users/micn/Documents/code/tbdex-pfi-exemplar/node_modules/@tbdex/http-client/dist/esm/src/client.js:162
        for (let jsonMessage of responseBody.data) {
                                             ^

TypeError: responseBody.data is not iterable
    at TbdexHttpClient.getExchange (file:///Users/micn/Documents/code/tbdex-pfi-exemplar/node_modules/@tbdex/http-client/dist/esm/src/client.js:162:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/micn/Documents/code/tbdex-pfi-exemplar/src/example/full-tbdex-exchange.ts:77:20)

Node.js v21.6.2
```

which seems to not like the data being returned from the http-server: 

```
{
    "data": {
        "rfq": {
            "metadata": {
                "from": "did:dht:nxs7cctyiwsyi4z9dci6xx917zs6s4krep5hkbrd4i3gqftkpu3o",
                "to": "did:dht:zij6d9sctkx4563mhjnkq19mapdxx4xtfo5hpm3cfq4wzwu5ofdo",
                "protocol": "1.0",
                "kind": "rfq",
                "id": "rfq_01hv0f4t1pewntf9zv28etd77f",
                "exchangeId": "rfq_01hv0f4t1pewntf9zv28etd77f",
                "createdAt": "2024-04-09T03:41:35.671Z"
            },
            "data": {
                "offeringId": "offering_01hv0f49v1f6dsh0pzgz2tkcd2",
                "payin": {
                    "amount": "42.42",
                    "kind": "CREDIT_CARD",
                    "paymentDetailsHash": "AJ6AVAXfSyWeaKdVQwvPtlztuTKoMwN9UydCkt0oe6E"
                },
                "payout": {
                    "kind": "AUSTRALIAN_BANK_ACCOUNT",
                    "paymentDetailsHash": "rSPF1lNG37kWRx5o1wlso_UQDI6l12TTBty8LgNkb_k"
                },
                "claimsHash": "LFVOG3pMI3pBeCn7m3ydriRb-0LYKx7R4PpzledY6VU"
            },
            "signature": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDpkaHQ6bnhzN2NjdHlpd3N5aTR6OWRjaTZ4eDkxN3pzNnM0a3JlcDVoa2JyZDRpM2dxZnRrcHUzbyMwIn0..w8b4Ff740snw0ELZrp2j40GbaYWGSDaFYOxpW9Uz0-SJPOSNbWdt4rK2nA-0WwZE8pt3LwkLAjhDUaG-ifnzAA",
            "privateData": {
                "salt": "f6xFmHeS4u1F3UV7zbWCdg",
                "payin": {
                    "paymentDetails": {
                        "cc_number": "5520000000000000",
                        "expiry_month": "05",
                        "expiry_year": "2024",
                        "cvc": "123",
                        "name": "Roland Robot"
                    }
                },
                "payout": {
                    "paymentDetails": {
                        "accountNumber": "987654321",
                        "bsbNumber": "123456",
                        "accountName": "Mr Roland Robot"
                    }
                },
                "claims": [
                    "eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRpZDpkaHQ6NDVicTVrc2thajU3cm9wdHNjY2RtY3U2cHJ6a3E1aXppZTdnOG5odWVyODcxZ21mMXg3byMwIn0.eyJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiU2FuY3Rpb25DcmVkZW50aWFsIl0sImlkIjoidXJuOnV1aWQ6YzQzODNiMTMtZTgzMi00OWRiLTkwNDgtZjdjZjhiODU3NDdiIiwiaXNzdWVyIjoiZGlkOmRodDo0NWJxNWtza2FqNTdyb3B0c2NjZG1jdTZwcnprcTVpemllN2c4bmh1ZXI4NzFnbWYxeDdvIiwiaXNzdWFuY2VEYXRlIjoiMjAyNC0wNC0wOVQwMzo0MTozNVoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDpkaHQ6bnhzN2NjdHlpd3N5aTR6OWRjaTZ4eDkxN3pzNnM0a3JlcDVoa2JyZDRpM2dxZnRrcHUzbyIsImJlZXAiOiJib29wIn19LCJuYmYiOjE3MTI2MzQwOTUsImp0aSI6InVybjp1dWlkOmM0MzgzYjEzLWU4MzItNDlkYi05MDQ4LWY3Y2Y4Yjg1NzQ3YiIsImlzcyI6ImRpZDpkaHQ6NDVicTVrc2thajU3cm9wdHNjY2RtY3U2cHJ6a3E1aXppZTdnOG5odWVyODcxZ21mMXg3byIsInN1YiI6ImRpZDpkaHQ6bnhzN2NjdHlpd3N5aTR6OWRjaTZ4eDkxN3pzNnM0a3JlcDVoa2JyZDRpM2dxZnRrcHUzbyIsImlhdCI6MTcxMjYzNDA5NX0.XUGn3ysB8dvbDnn3yWRiSakgRKbF5ujWzE-nRlKQNXQDpyyITuMVBjWccHPFOUo8V8mhage513SeKj2Cq7w7AA"
                ]
            }
        },
        "quote": {
            "metadata": {
                "from": "did:dht:zij6d9sctkx4563mhjnkq19mapdxx4xtfo5hpm3cfq4wzwu5ofdo",
                "to": "did:dht:nxs7cctyiwsyi4z9dci6xx917zs6s4krep5hkbrd4i3gqftkpu3o",
                "exchangeId": "rfq_01hv0f4t1pewntf9zv28etd77f",
                "protocol": "1.0",
                "kind": "quote",
                "id": "quote_01hv0f4vkpea89w95v8ee7xvv0",
                "createdAt": "2024-04-09T03:41:37.270Z"
            },
            "data": {
                "expiresAt": "2028-04-30T14:00:00.000Z",
                "payin": {
                    "currencyCode": "USD",
                    "amount": "42.42"
                },
                "payout": {
                    "currencyCode": "AUD",
                    "amount": "46.66"
                }
            },
            "signature": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDpkaHQ6emlqNmQ5c2N0a3g0NTYzbWhqbmtxMTltYXBkeHg0eHRmbzVocG0zY2ZxNHd6d3U1b2ZkbyMwIn0.._5jDxv6iP0dSTMC86gPfytyWZU1C1iQmWRT11uSwRyyXtTKR9Nlpef-UKldpBZgGFAPz1v_Bg3fsddSxz1xPAg"
        },
        "orderstatus": []
    }
}
```

any ideas? there is a quote in there, and it is trying to fetch it using getExchange - but it expects a list

**Comment by michaelneale** [comment]
to reproduce can try running through this: 

https://github.com/TBD54566975/tbdex-pfi-exemplar/pull/29

but I suspect any code using server/client would hit this

**Comment by michaelneale** [comment]
I patched around it here: https://github.com/TBD54566975/tbdex-pfi-exemplar/pull/29/commits/16c7a39b3642241e6820f2d7b1840d47d70881de#diff-fe04e790b4f139eddfbfc8783276e09d6cb49c73f3be51cc2fffdd4825498343R208 - as that reflects the data actually returned by http-server
